# Introduction
There are approximately 460 Conservation Units (CUs) of Pacific salmon, of which a significant proportion have been assessed or are expected to be assessed with poor status below conservation thresholds. Rebuilding plans are now required for major stocks (aggregates of CUs that are managed together) that drop below limit reference points under the revised Fisheries Act [@DFO2019]. In addition, Canada’s Wild Salmon Policy specifies that actions should be considered to rebuild CUs when they drop below lower biological benchmarks. However, progress on developing rebuilding plans has been limited, in part because of a lack of tools to identify and evaluate management actions for depleted CUs. Once identified, fisheries managers face the additional challenge of identifying how to best achieve CU-specific targets within multiple mixed-CU fisheries.

Our overall goal was to create a simulation tool to inform the development and evaluation of harvest components of rebuilding plans for Pacific salmon, which evaluates trade-offs between conservation objectives and other fisheries management objectives. In the first phase of this project, we developed a prototype of the tool to evaluate the extent to which reductions in harvest impact rebuilding potential, if at all, and explore how to achieve rebuilding targets in the context of multiple mixed-stock fisheries. In addition, we considered environmental forcing of population dynamics that may impact productivity and confound recovery efforts. The rebuilding tool was scoped to focus on harvest actions before more detailed strategies that integrate multiple management interventions (e.g., habitat and hatcheries) can be developed to support rebuilding. The outcomes from this project are intended to form the first step in the development of an integrated rebuilding plan that includes engagement with First Nations and stakeholders. We applied the prototype to two case studies, a data-rich and data-poor example, which can be expanded in future phases within a broader simulation framework and context of multiple stressors (Management Strategy Evaluation, MSE). 

## Policy Context 
DFO’s Fisheries Decision-Making Framework Incorporating the Precautionary Approach (Precautionary Approach Framework @dfo2009) provides guidance on how to manage fisheries in a precautionary manner. This framework states that “when a stock has reached the Critical Zone, a rebuilding plan must be in place with the aim of having a high probability of the stock growing out of the Critical Zone within a reasonable timeframe”. Further direction is provided in DFO’s “Guidance for the Development of Rebuilding Plans under the Precautionary Approach Framework: Growing Stocks out of the Critical Zone” (Guidance on Rebuilding), an annex of the Precautionary Approach Framework. This guidance document recommends the development of simulation models within the context of Management Strategy Evaluations (MSEs) to examine the consequences of alternative management measures aimed at rebuilding depleted stocks under different plausible hypotheses about uncertain population and fisheries dynamics. It states that transparency in responding to trade-offs among objectives (e.g., conservation and socio-economic) is essential for effective decision making, and that MSE can aid in building in stronger relationships among DFO, First Nations, and stakeholders, fostering open and transparent decision making. Given expectations from First Nations for increased collaboration and involvement in decision-making, MSE may provide a platform for this engagement. 

The revised Fisheries Act [@DFO2019] further requires the development and implementation of rebuilding plans for major stocks that fall below limit reference points. Although rebuilding plans will be developed at the scale of stock management units for Pacific salmon, these need to consider the conservation of diversity at the scale of CUs. Guidance on developing rebuilding plans under the Fisheries Act is currently in development.

In addition, the Wild Salmon Policy (WSP) aims to restore and protect healthy and diverse salmon CUs and their habitats, where diversity of Pacific salmon is protected, in part, through preserving CUs. A significant portion of the approximately 460 CUs of Pacific salmon have been assessed, or are expected to be assessed, with poor status below conservation thresholds (below lower benchmarks resulting in status in the “red zone”). The WSP [@DFO2005] states, 

*A CU in the red zone is undesirable because of the risk of extirpation and the loss of ecological benefits and salmon production. The presence of a CU in the red zone will initiate an immediate consideration of ways to protect the fish, increase their abundance and reduce the risk of loss. Biological considerations will be the primary driver for the management of CUs with red status.*

The WSP also states that sustainable use and managing fisheries for sustainable benefits are important considerations for managing CUs. Accordingly, rebuilding efforts will need to consider social and economic impacts as well as conservation objectives. Trade-offs among conservation and short- and long-term social and economic objectives should be made in a clear and transparent manner. Indeed, the fourth principle of the WSP requires that decision-making be transparent and inclusive. 

The 2018 Implementation Plan for the WSP identified a gap between DFO’s current response to depleted CUs and that required in the WSP [@DFO2018]. The Implementation Plan includes the development of long-term strategic plans for rebuilding priority CUs or management units (aggregates of CUs). However, progress on implementing rebuilding strategies within Integrated Fisheries Management Plans or other processes has been limited, in part due to a lack of quantitative tools to evaluate alternative harvest strategies proposed within rebuilding plans.

Furthermore, the Committee on the Status of Endangered Wildlife in Canada, COSEWIC has assessed 10 Fraser River Sockeye Salmon Designatable Units (DUs, the unit of conservation identified by COSEWIC), 12 Southern BC Chinook Salmon DUs, and 1 Interior Fraser Coho Salmon DU as threatened or endangered. Recovery Potential Assessments have been or are being developed for these DUs, which include forward projection tools that demonstrate the recovery potential of current and alternative mortality rates. However, those models typically lack sufficiently detailed harvest strategies to provide realistic guidance to managers about harvest options. The primary goal of Recovery Potential Assessments is to identify the overall potential for recovery and not to evaluate trade-offs among harvest control rules in their performance against multiple objectives. 

The significant impacts of climate and environmental conditions on fish stocks are recognized in DFO’s Guidance on Rebuilding, which states that, “the influence of environmental conditions on rebuilding should be considered and incorporated into rebuilding efforts for depleted stocks”. To inform these rebuilding efforts, DFO has developed a National Working Group on an Ecosystem Approach to Fisheries Management. More broadly, the ability to achieve management goals is impacted by climate and environmental variability and international best practices include the development of simulation tools to evaluate management strategies under a range of plausible hypotheses about climate impacts [@king2015; @punt2014]. 

The proposed tool fills these some of these gaps by evaluating trade-offs among conservation and harvest objectives for candidate harvest control rules of Pacific salmon, including those within mixed-CU fisheries containing weak and productive CUs, and considering various future scenarios for climate and environmental conditions.
