# Next Steps and Recommendations

Several potential additional model components were identified in collaboration with Fisheries Management at a Workshop April 2019 to better inform rebuilding plans under the Fisheries Act and the Wild Salmon Policy, and recovery strategies under the Species at Risk Act, SARA.

- The current modelling tool could be adapted to readily calculate and compare the time for rebuilding under pessimistic and optimistic harvest scenarios. These types of metrics have the potential to identify CUs for which harvest poses a high risk to rebuilding, as in the US by the National Marine Fisheries Service (NMFS) e.g., as described by @wetzel2016 and @benson2016. If the rebuilding times do not change with extreme harvest scenarios, then this would signal that rebuilding plans should focus on alternative threats, beyond harvest. Identifying  metrics such as these in a structured and repeatable way would be beneficial for COSEWIC Recovery Potential Assessments, SARA Recovery Strategies, and Bill C-68 Rebuilding Plans. The modelling tool that has been developed for this project could be adapted to calculate these types of metrics.

- The model could include a greater selection of generic harvest strategies to capture the basic management types for Pacific salmon. For example, fixed escapement goal and abundance-based escapement goals could augment currently available HCRs (fixed exploitation rate and abundance-base exploitation rate).

- The model's forecast component could be directly incorporated into HCRs to represent MUs with abundance-based HCRs where forecasts or in-season assessments are required to set harvest rates or escapement goals.

- The model could include changes in capacity over time within the spawner-recruitment relationship to represent deteriorating habitat conditions or habitat mitigation efforts. Information on changes in capacity could be derived from RAMS, Risk Assessment Methodology for Salmon, output [@hyatt2017; @DFO2018]. In addition, both enhancement and habitat mitigation levers could be added to the management procedure to more fully capture rebuilding options.

- The model could be adapted to directly incorporate environmental covariates (e.g., abundance of competitors, sea surface temperature) in the stock-recruit relationship. Previously published estimates of the strengths of these effects [@connors2020] would be used to realistically parameterize the operating model. Analysts could then determine to what extent recovery may be constrained by basin-scale environmental processes.

- The model could consider variable weights for CUs within performance measures. For example, if one CU has high recovery potential or is prioritized by a large number of stakeholders, decision-makers may wish to weight it higher than others when looking at aggregate performance. 

- For mixed-stock fisheries, CU-specific harvest control rules could be included in future iterations including, for example, Excess Salmon to Spawning Requirements, ESSR, and Food Social and Ceremonital, FSC fisheries; however, these would require detailed input from Fisheries Management and need to be developed on a case-by-case basis.

- There is a potential to apply this tool to more complicated multi-species fisheries in which MPs are evaluated against objectives for both target and non-target species. This type of functionality will be important for stocks like natural-origin Coho salmon in which impacts come primarily from incidental catch from fisheries on other species. While a case study such as this has not yet been examined, fisheries within the model could be structured to represent non-target fisheries and, potentially, multiple species, though these changes would dramatically increase the complexity of the model due to differences in age structure. 

- It may be possible to evaluate the impacts of changes in assessment frequency and intensity using proxies in the simulation model by changing the variances in observation errors in the assessment sub-model and adding possible biases. Also, it may be possible to approximate those variances retrospectively with historical data. This module could answer important questions about the potential benefits of additional assessment or implications of the further loss of assessment programs.

- There may be value in combining this tool with RAMS and Priority Threat Management, PTM at different spatial scales. For example, information on changes in capacity from watershed-level RAMS could be included in CU-specific parameterizations of stock-recruitment relationships in this tool. Threats identified from PTM could be included in this model, and this model could identify where harvest is not a primary threat and others should be identified within PTM.


## Recommendations for developing decision-support tools for Pacific salmon

The `samSim` model described in this report represents one of many available decision-support tools that can be used to inform fisheries management. `samSim` focuses on a detailed quantitative analysis of a narrow aspect of recovery planning (harvest decision-making), while other tools exist that take a more comprehensive but qualitative approach to evaluating recovery options. Although we have made initial suggestions about how `samSim` could be used in conjunction with some of these other tools, we recommend that a review of various decision-support tools for the management of Pacific salmon be included in a strategic plan or a guidance document for Pacific salmon, providing advice on the conditions under which each tool is most useful including costs and resource requirements. Lessons learnt from application of various tools could be compiled in a report to inform this review.  For examples, keys to success of RAMS have been identified from case studies, e.g., on Barkley Sound where the use of a skilled facilitator to elicit expert opinion on key parameters was beneficial. In addition, Kronlund et al. [-@kronlund2016] identified necessary conditions for MSE when informing fisheries management within DFO. Limitations to the application of MSEs are also described in Kronlund and Marentette [-@kronlund2019]. A first step is for DFO Science to develop a table of potential decision-support tools for consideration. 

A gap highlighted by project participants was the failure to rigorously include socioeconomic and cultural objectives when identifying trade-offs among management procedures. The inclusion of social scientists may be necessary to elicit these socio-economic and cultural objectives and would contribute to success of the process by better capturing the underlying values of partners.
