---
title: "A quantitative tool for evaluating rebuilding plans for Pacific salmon"
year: 2020
report_number: 3402
author: |
  Carrie A. Holt,
  Cameron Freshwater,
  Kendra R. Holt,
  Ann-Marie Huang
author_list: "Holt, C.A., Freshwater, C., Holt, K., and Huang, A.-M."
region: Pacific Region
isbn: 978-0-660-35946-5
address: |
  Pacific Biological Station\
     Fisheries and Oceans Canada, 3190 Hammond Bay Road\
     Nanaimo, British Columbia, V9T 6N7, Canada\
phone: "(250) 756-7136"
author_footnote: "Email: Carrie.Holt@dfo-mpo.gc.ca | telephone: (250) 756-7136"
abstract: |
  Rebuilding plans are required for depleted stocks under the Fish Stock Provisions of Canada’s revised Fisheries Act (2019) and DFO’s Sustainable Fisheries Framework (2009). The overall goal of this project was to create a tool for developing and evaluating the harvest component of rebuilding plans for Pacific salmon, which evaluates trade-offs between conservation objectives and other fisheries management objectives. This rebuilding tool, called `samSim` can be used to explore performance of candidate rebuilding harvest strategies in the context of multiple mixed-stock fisheries and environmental forcing of population dynamics that may impact productivity and confound recovery efforts. `samSim` was scoped to focus on harvest actions before more detailed strategies that integrate multiple management interventions (e.g., habitat and hatcheries) can be developed to support rebuilding.  The outcomes from this project are intended to form a possible first step towards an integrated rebuilding plan that includes First Nations and stakeholders. In this first phase, we applied the `samSim` to two case studies: Fraser Rivers sockeye salmon, a data-rich example, and Nass River chum salmon, which was relatively data limited. `samSim` can be expanded in future phases within a broader simulation framework and context of multiple stressors. The tool, `samSim`,  is freely accessible and documented in a public repository online. 
abstract_other: |
  Des plans de rétablissement sont requis en raison des stocks épuisés en vertu des dispositions sur les stocks de poissons de la version révisée de la Loi sur les pêches du Canada (2019) et du Cadre pour la pêche durable du MPO (2009). L’objectif global de ce projet était de créer un outil pour l’élaboration et l’évaluation du volet pêche des plans de rétablissement du saumon du Pacifique, qui évalue les compromis entre les objectifs de conservation et les autres objectifs de gestion des pêches. Cet outil de rétablissement, appelé `samSim`, peut être utilisé pour explorer la performance des stratégies étudiées de reconstitution des stocks dans le contexte de multiples pêches de stocks mixtes et du forçage environnemental de la dynamique des populations qui peuvent avoir une incidence sur la productivité et brouiller les efforts de rétablissement. L’outil `samSim` a été conçu pour mettre l’accent sur les mesures de récolte avant que des stratégies plus détaillées qui intègrent de multiples interventions de gestion (p. ex., habitat et écloseries) puissent être élaborées pour appuyer le rétablissement. Les résultats de ce projet visent à constituer une première étape possible vers un plan de rétablissement intégré qui inclut les Premières Nations et les intervenants. Dans cette première phase, nous avons appliqué `samSim` à deux études de cas : le saumon rouge du fleuve Fraser, un exemple riche en données, et le saumon kéta de la rivière Nass, qui était relativement limité en données. L’outil `samSim` peut être étendu dans les phases futures dans un cadre de simulation élargi et dans un contexte de facteurs de stress multiples. L’outil `samSim` est accessible librement et documenté dans un dépôt public en ligne.
output:
 csasdown::techreport_pdf:
 #csasdown::techreport_word:
   french: false
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
csl: csl/csas.csl
lot: true
lof: true
# Any extra LaTeX code for the header:
# header-includes:
# - \usepackage{tikz}
---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
# adjust as desired:
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = if (knitr:::is_latex_output()) "knitr-figs-pdf/" else "knitr-figs-docx/",
  cache.path = if (knitr:::is_latex_output()) "knitr-cache-tex/" else "knitr-cache-docx/",
  fig.asp = 0.618,
  fig.width = 9,
  out.width = "6in",
  echo = FALSE,
#  autodep = TRUE,
#  cache = TRUE,
  cache.comments = FALSE,
  dev = if (knitr:::is_latex_output()) "png" else "png",
  dpi = 180,
  fig.align = "center",
  fig.pos = "htb")
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# add other packages here:
library(csasdown)
library(tidyverse)
library(kableExtra)
```
